### PR TITLE
Add static screen tutorials

### PR DESCRIPTION
**Pull request by pearlyong**

### CODE REVIEW

**Comment by chongzixin** [comment]
Do you want to link them to the /instructions page too? Or leave those as videos first while we test this on Day 3 sms?

**Comment by pearlyong** [comment]
I think for this experiment, let's leave this page as it is because it might confuse them if we show them links to video tutorials as well.

**Comment by chongzixin** [comment]
Eh sorry what I meant is do you want to also update step 10 of https://homer.gov.sg/instructions to use these static pages instead of videos?

**Comment by pearlyong** [comment]
Ah I see, let's hold off until after the experiment and we are sure that the static screens work better?

**Pull request merged**
